### ISSUE TITLE
An Issue With a Mouse Wheel

### ISSUE THREAD

**Issue by y-vasyunin** [NationalSecurityAgency/qgis-lockzoom-plugin#1]
I think it's a bug. Otherwise, I can't imagine why it happens like this. After I click the plugin button, a base map sticks with a specific scale as intended. Labels look much better now! Then I scroll a mouse wheel to zoom in or out, and it makes the map panning in various directions. It is very confusing. After I "insist" with scrolling, the map jumps to the next/previous zoom level. I tried it on Mac OS Catalina (10.15.3), 3.12.0-București, Plugin version 3.0.1.

I took [a short video](https://youtu.be/wf1ORRBuZw8) with the demonstration. Note that on the video I don't pan the map — I just scroll the mouse wheel.

**Comment by hamiltoncj** [comment]
Thanks for your report. I have checked this against a Windows install and it works correctly. Unfortunately, I don't have a mac to try it with. There are several QGIS API calls I make to determine the scale. I am guessing that they are not working properly on the Mac QGIS installation. Currently I am on lock down due to the COVID-19 craziness. I should probably test this with LINUX to see what it does, but I am not sure when I will be able to investigate this more. If you happen to have LINUX or Windows it would be nice if you could test it on those platforms.

**Comment by y-vasyunin** [comment]
I tested it in VirtualBox with Lubuntu 18.04.4 and QGIS 3.4.11-Madeira. It seems to work when the **zoom factor** is set to default 200% (**Options->Map Tools->Zooming**). If I change the zoom factor to 100% to get smooth zooming, then the same issue with the map that starts to drag around reproduces. But this time it doesn't even jump to the next/previous zoom level.
 
I also tried to run it in a Parallels VM with Windows 10 and QGIS 3.10.1-A Coruña. The same.

I work on a MacBook with an external display and a mouse. I tried to use only Mac's touchpad, and I got the same issue when a map starts to pan instead of zooming. If you need any additional info, just ask.

**Comment by hamiltoncj** [comment]
Thanks for that clarification. This plugin will not work if you set the zoom factor to 100% and then try to zoom in or out. The reason is because it is trying to match the QGIS zoom level to the scale of cached image tiles. With the plugin enabled, each time you zoom in or out it checks the current scale with one of the tile cache scales and changes the zoom to match that scale. Tile cache scale changes by a factor of 2. If your zoom factor is 100% you are just incrementally zooming in or out. You haven't zoomed in or out enough to jump to the next tile cache zoom factor and so it just resets itself to the closest zoom factor which is the one you were already at.

The zoom factor of 200% is the ideal setting because it doubles the scale factor each time you zoom in and out and will match the tile cache scales. It does not make sense to have a zoom setting of 100% with this plugin because you only get clear text from a tile cache if you are matching the zoom levels of the tile cache.

I probably should including a warning with the plugin if the zoom factor is not set to 200%, 300%, 400%, etc.

I wouldn't characterize this as a bug, but I do need to clarify why it needs to be set to at least 200%.

Thank you for bring this to my attention and I hope this helps to understand why the plugin works the way it works.

**Comment by y-vasyunin** [comment]
Sorry I wasn't clear enough. It's true what you said for my Lubuntu testing but on Windows and Mac OS, **when the zoom level is set to 200%**, the map goes randomly panned around (at least I can't catch any order in it) before it actually zooms to another level (as in the video attached above). That is what I mean to be a bug.

**Comment by hamiltoncj** [comment]
I can't seem to replicate the behavior on my laptop. Since I am on lock down it will probably be at least a week and a half before I will be able to investigate on other systems.

**Comment by hamiltoncj** [comment]
Closing the ticket because I was never able to replicate it.
